// app/api/profile/update/route.ts
import { NextRequest, NextResponse } from 'next/server'
import { prisma } from '@/lib/prisma'

export async function PATCH(req: NextRequest) {
  try {
    const userId = req.headers.get('x-user-id')
    if (!userId) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
    }

    const body = await req.json()
    const {
      fullName,
      gender,
      dateOfBirth,
      bio,
      height,
      religion,
      caste,
      motherTongue,
      education,
      educationLevel,
      occupation,
      occupationCategory,
      annualIncome,
      city,
      state,
      maritalStatus,
      physicalStatus,
      profileCreatedBy,
      employmentType,
      country,
      citizenship,
      eatingHabit,
      smokingHabit,
      drinkingHabit,
      hobbies,
      familyStatus,
      familyValue,
      familyType,
      horoscopeAvailable,
      horoscopeUrl,
      rashi,
      nakshatra,
      dosham,
      partnerAgeMin,
      partnerAgeMax,
      partnerReligion,
      partnerCaste,
      partnerEducationLevel,
      partnerOccupationCategory,
      partnerCity,
      partnerState,
      partnerHeightMin,
      partnerHeightMax,
      partnerMotherTongue,
      partnerMaritalStatus,
      partnerEatingHabit,
      partnerSmokingHabit,
      partnerDrinkingHabit,
      partnerCountry,
      partnerDosham,
      avatarUrl,
      coverUrl,
    } = body

    const [updatedUser] = await prisma.$transaction([
      prisma.user.update({
        where: { id: userId },
        data: {
          ...(fullName !== undefined && { fullName }),
          ...(gender !== undefined && { gender }),
          ...(dateOfBirth !== undefined && { dateOfBirth: new Date(dateOfBirth) }),
        },
      }),
      prisma.profile.upsert({
        where: { userId },
        create: {
          userId,
          bio,
          height,
          religion,
          caste,
          motherTongue,
          education,
          educationLevel,
          occupation,
          occupationCategory,
          annualIncome,
          city,
          state,
          maritalStatus,
          physicalStatus,
          profileCreatedBy,
          employmentType,
          country,
          citizenship,
          eatingHabit,
          smokingHabit,
          drinkingHabit,
          hobbies: hobbies ?? [],
          familyStatus,
          familyValue,
          familyType,
          horoscopeAvailable: horoscopeAvailable ?? false,
          horoscopeUrl,
          rashi,
          nakshatra,
          dosham,
          partnerAgeMin,
          partnerAgeMax,
          partnerReligion,
          partnerCaste,
          partnerEducationLevel,
          partnerOccupationCategory,
          partnerCity,
          partnerState,
          partnerHeightMin,
          partnerHeightMax,
          partnerMotherTongue,
          partnerMaritalStatus,
          partnerEatingHabit,
          partnerSmokingHabit,
          partnerDrinkingHabit,
          partnerCountry,
          partnerDosham,
          avatarUrl,
          coverUrl,
        },
        update: {
          ...(bio !== undefined && { bio }),
          ...(height !== undefined && { height }),
          ...(religion !== undefined && { religion }),
          ...(caste !== undefined && { caste }),
          ...(motherTongue !== undefined && { motherTongue }),
          ...(education !== undefined && { education }),
          ...(educationLevel !== undefined && { educationLevel }),
          ...(occupation !== undefined && { occupation }),
          ...(occupationCategory !== undefined && { occupationCategory }),
          ...(annualIncome !== undefined && { annualIncome }),
          ...(city !== undefined && { city }),
          ...(state !== undefined && { state }),
          ...(maritalStatus !== undefined && { maritalStatus }),
          ...(physicalStatus !== undefined && { physicalStatus }),
          ...(profileCreatedBy !== undefined && { profileCreatedBy }),
          ...(employmentType !== undefined && { employmentType }),
          ...(country !== undefined && { country }),
          ...(citizenship !== undefined && { citizenship }),
          ...(eatingHabit !== undefined && { eatingHabit }),
          ...(smokingHabit !== undefined && { smokingHabit }),
          ...(drinkingHabit !== undefined && { drinkingHabit }),
          ...(hobbies !== undefined && { hobbies }),
          ...(familyStatus !== undefined && { familyStatus }),
          ...(familyValue !== undefined && { familyValue }),
          ...(familyType !== undefined && { familyType }),
          ...(horoscopeAvailable !== undefined && { horoscopeAvailable }),
          ...(horoscopeUrl !== undefined && { horoscopeUrl }),
          ...(rashi !== undefined && { rashi }),
          ...(nakshatra !== undefined && { nakshatra }),
          ...(dosham !== undefined && { dosham }),
          ...(partnerAgeMin !== undefined && { partnerAgeMin }),
          ...(partnerAgeMax !== undefined && { partnerAgeMax }),
          ...(partnerReligion !== undefined && { partnerReligion }),
          ...(partnerCaste !== undefined && { partnerCaste }),
          ...(partnerEducationLevel !== undefined && { partnerEducationLevel }),
          ...(partnerOccupationCategory !== undefined && { partnerOccupationCategory }),
          ...(partnerCity !== undefined && { partnerCity }),
          ...(partnerState !== undefined && { partnerState }),
          ...(partnerHeightMin !== undefined && { partnerHeightMin }),
          ...(partnerHeightMax !== undefined && { partnerHeightMax }),
          ...(partnerMotherTongue !== undefined && { partnerMotherTongue }),
          ...(partnerMaritalStatus !== undefined && { partnerMaritalStatus }),
          ...(partnerEatingHabit !== undefined && { partnerEatingHabit }),
          ...(partnerSmokingHabit !== undefined && { partnerSmokingHabit }),
          ...(partnerDrinkingHabit !== undefined && { partnerDrinkingHabit }),
          ...(partnerCountry !== undefined && { partnerCountry }),
          ...(partnerDosham !== undefined && { partnerDosham }),
          ...(avatarUrl !== undefined && { avatarUrl }),
          ...(coverUrl !== undefined && { coverUrl }),
        },
      }),
    ])

    return NextResponse.json({ message: 'Profile updated' })
  } catch (err) {
    console.error('Update profile error:', err)
    return NextResponse.json({ error: 'Something went wrong' }, { status: 500 })
  }
}