// app/api/profile/update/route.ts
import { NextRequest, NextResponse } from 'next/server'
import { prisma } from '@/lib/prisma'

export async function PATCH(req: NextRequest) {
  try {
    const userId = req.headers.get('x-user-id')
    if (!userId) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
    }

    const body = await req.json()
    const {
      fullName,
      gender,
      dateOfBirth,
      bio,
      height,
      weightKg,
      bodyType,
      religion,
      caste,
      gothram,
      motherTongue,
      education,
      educationLevel,
      occupation,
      occupationCategory,
      collegeInstitution,
      organizationName,
      annualIncome,
      state,
      district,
      ancestralOrigin,
      maritalStatus,
      physicalStatus,
      profileCreatedBy,
      employmentType,
      eatingHabit,
      smokingHabit,
      drinkingHabit,
      hobbies,
      spokenLanguages,
      familyStatus,
      familyValue,
      familyType,
      fatherOccupation,
      fatherIncome,
      motherOccupation,
      motherIncome,
      brothersCount,
      brothersMarried,
      sistersCount,
      sistersMarried,
      familyBio,
      horoscopeAvailable,
      horoscopeUrl,
      rashi,
      nakshatra,
      dosham,
      partnerAgeMin,
      partnerAgeMax,
      partnerHeightMin,
      partnerHeightMax,
      partnerReligion,
      partnerCaste,
      partnerMotherTongue,
      partnerMaritalStatus,
      partnerEducationLevel,
      partnerOccupationCategory,
      partnerEmploymentType,
      partnerState,
      partnerDistrict,
      partnerEatingHabit,
      partnerSmokingHabit,
      partnerDrinkingHabit,
      partnerPhysicalStatus,
      partnerFamilyStatus,
      partnerFamilyValue,
      partnerFamilyType,
      partnerDosham,
      partnerNakshatra,
      partnerSpokenLanguages,
      avatarUrl,
      coverUrl,
    } = body

    const [updatedUser] = await prisma.$transaction([
      prisma.user.update({
        where: { id: userId },
        data: {
          ...(fullName !== undefined && { fullName }),
          ...(gender !== undefined && { gender }),
          ...(dateOfBirth !== undefined && { dateOfBirth: new Date(dateOfBirth) }),
        },
      }),
      prisma.profile.upsert({
        where: { userId },
        create: {
          userId,
          bio,
          height,
          weightKg,
          bodyType,
          religion,
          caste,
          gothram,
          motherTongue,
          education,
          educationLevel,
          occupation,
          occupationCategory,
          collegeInstitution,
          organizationName,
          annualIncome,
          state,
          district,
          ancestralOrigin,
          maritalStatus,
          physicalStatus,
          profileCreatedBy,
          employmentType,
          eatingHabit,
          smokingHabit,
          drinkingHabit,
          hobbies: hobbies ?? [],
          spokenLanguages: spokenLanguages ?? [],
          familyStatus,
          familyValue,
          familyType,
          fatherOccupation,
          fatherIncome,
          motherOccupation,
          motherIncome,
          brothersCount,
          brothersMarried,
          sistersCount,
          sistersMarried,
          familyBio,
          horoscopeAvailable: horoscopeAvailable ?? false,
          horoscopeUrl,
          rashi,
          nakshatra,
          dosham,
          partnerAgeMin,
          partnerAgeMax,
          partnerHeightMin,
          partnerHeightMax,
          partnerReligion,
          partnerCaste,
          partnerMotherTongue,
          partnerMaritalStatus,
          partnerEducationLevel,
          partnerOccupationCategory,
          partnerEmploymentType,
          partnerState,
          partnerDistrict,
          partnerEatingHabit,
          partnerSmokingHabit,
          partnerDrinkingHabit,
          partnerPhysicalStatus,
          partnerFamilyStatus,
          partnerFamilyValue,
          partnerFamilyType,
          partnerDosham,
          partnerNakshatra,
          partnerSpokenLanguages: partnerSpokenLanguages ?? [],
          avatarUrl,
          coverUrl,
        },
        update: {
          ...(bio !== undefined && { bio }),
          ...(height !== undefined && { height }),
          ...(weightKg !== undefined && { weightKg }),
          ...(bodyType !== undefined && { bodyType }),
          ...(religion !== undefined && { religion }),
          ...(caste !== undefined && { caste }),
          ...(gothram !== undefined && { gothram }),
          ...(motherTongue !== undefined && { motherTongue }),
          ...(education !== undefined && { education }),
          ...(educationLevel !== undefined && { educationLevel }),
          ...(occupation !== undefined && { occupation }),
          ...(occupationCategory !== undefined && { occupationCategory }),
          ...(collegeInstitution !== undefined && { collegeInstitution }),
          ...(organizationName !== undefined && { organizationName }),
          ...(annualIncome !== undefined && { annualIncome }),
          ...(state !== undefined && { state }),
          ...(district !== undefined && { district }),
          ...(ancestralOrigin !== undefined && { ancestralOrigin }),
          ...(maritalStatus !== undefined && { maritalStatus }),
          ...(physicalStatus !== undefined && { physicalStatus }),
          ...(profileCreatedBy !== undefined && { profileCreatedBy }),
          ...(employmentType !== undefined && { employmentType }),
          ...(eatingHabit !== undefined && { eatingHabit }),
          ...(smokingHabit !== undefined && { smokingHabit }),
          ...(drinkingHabit !== undefined && { drinkingHabit }),
          ...(hobbies !== undefined && { hobbies }),
          ...(spokenLanguages !== undefined && { spokenLanguages }),
          ...(familyStatus !== undefined && { familyStatus }),
          ...(familyValue !== undefined && { familyValue }),
          ...(familyType !== undefined && { familyType }),
          ...(fatherOccupation !== undefined && { fatherOccupation }),
          ...(fatherIncome !== undefined && { fatherIncome }),
          ...(motherOccupation !== undefined && { motherOccupation }),
          ...(motherIncome !== undefined && { motherIncome }),
          ...(brothersCount !== undefined && { brothersCount }),
          ...(brothersMarried !== undefined && { brothersMarried }),
          ...(sistersCount !== undefined && { sistersCount }),
          ...(sistersMarried !== undefined && { sistersMarried }),
          ...(familyBio !== undefined && { familyBio }),
          ...(horoscopeAvailable !== undefined && { horoscopeAvailable }),
          ...(horoscopeUrl !== undefined && { horoscopeUrl }),
          ...(rashi !== undefined && { rashi }),
          ...(nakshatra !== undefined && { nakshatra }),
          ...(dosham !== undefined && { dosham }),
          ...(partnerAgeMin !== undefined && { partnerAgeMin }),
          ...(partnerAgeMax !== undefined && { partnerAgeMax }),
          ...(partnerHeightMin !== undefined && { partnerHeightMin }),
          ...(partnerHeightMax !== undefined && { partnerHeightMax }),
          ...(partnerReligion !== undefined && { partnerReligion }),
          ...(partnerCaste !== undefined && { partnerCaste }),
          ...(partnerMotherTongue !== undefined && { partnerMotherTongue }),
          ...(partnerMaritalStatus !== undefined && { partnerMaritalStatus }),
          ...(partnerEducationLevel !== undefined && { partnerEducationLevel }),
          ...(partnerOccupationCategory !== undefined && { partnerOccupationCategory }),
          ...(partnerEmploymentType !== undefined && { partnerEmploymentType }),
          ...(partnerState !== undefined && { partnerState }),
          ...(partnerDistrict !== undefined && { partnerDistrict }),
          ...(partnerEatingHabit !== undefined && { partnerEatingHabit }),
          ...(partnerSmokingHabit !== undefined && { partnerSmokingHabit }),
          ...(partnerDrinkingHabit !== undefined && { partnerDrinkingHabit }),
          ...(partnerPhysicalStatus !== undefined && { partnerPhysicalStatus }),
          ...(partnerFamilyStatus !== undefined && { partnerFamilyStatus }),
          ...(partnerFamilyValue !== undefined && { partnerFamilyValue }),
          ...(partnerFamilyType !== undefined && { partnerFamilyType }),
          ...(partnerDosham !== undefined && { partnerDosham }),
          ...(partnerNakshatra !== undefined && { partnerNakshatra }),
          ...(partnerSpokenLanguages !== undefined && { partnerSpokenLanguages }),
          ...(avatarUrl !== undefined && { avatarUrl }),
          ...(coverUrl !== undefined && { coverUrl }),
        },
      }),
    ])

    return NextResponse.json({ message: 'Profile updated' })
  } catch (err) {
    console.error('Update profile error:', err)
    return NextResponse.json({ error: 'Something went wrong' }, { status: 500 })
  }
}